# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- develop
- tf.keras-version

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    # base dependencies
    pip install .
    pip install jieba
    pip install tensorflow==1.13.1
    # CI dependencies
    pip install python-coveralls coverage flake8 flake8-builtins
    pip install pytest pytest-azurepipelines pytest-cov
    pip install nose
    # pip install flake8-docstrings
  displayName: 'Install dependencies'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: azure
    organization: 'brikerman-github'
    projectKey: 'BrikerMan_Kashgari'
    projectName: Kashgari
    scannerMode: CLI
    extraProperties: |
     # Additional properties that will be passed to the scanner, 
     # Put one key=value per line, example:
     # sonar.exclusions=**/*.bin
     # sonar.python.coverage.reportPaths=$(System.DefaultWorkingDirectory)/test-cov.xml

- script: |
    flake8 kashgari
  displayName: 'Flake 8 Style check'

- script: |
    - script: |
    nosetests --with-coverage --cover-html --cover-html-dir=htmlcov --cover-xml --cover-xml-file=coverage.xml --with-xunit --cover-package="kashgari" tests/
  displayName: 'nosetests'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'